version: '3.8'
services:

  # Eureka Server
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - phegon-net

  # Booking Service (PostgreSQL + MinIO)
  # booking-service:
  #   build:
  #     context: ./booking-service
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/booking_db
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres
  #     - MINIO_ENDPOINT=http://minio:9000
  #     - MINIO_ACCESS_KEY=admin
  #     - MINIO_SECRET_KEY=admin123
  #   depends_on:
  #     - postgres
  #     - minio
  #     - eureka-server
  #   networks:
  #     - phegon-net

  # # Room Service (MySQL)
  # room-service:
  #   build:
  #     context: ./room-service
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-room:3306/room_db
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=root
  #   depends_on:
  #     - mysql-room
  #     - eureka-server
  #   networks:
  #     - phegon-net

  # User Service (MySQL)
  # user-service:
  #   build:
  #     context: ./user-service
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/user_db
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=root
  #   depends_on:
  #     - mysql-user
  #     - eureka-server
  #   networks:
  #     - phegon-net

  # # Auth Service (giả định dùng chung DB với user)
  # auth-service:
  #   build:
  #     context: ./auth-service
  #   ports:
  #     - "8084:8084"
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/user_db
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=root
  #   depends_on:
  #     - mysql-user
  #     - eureka-server
  #   networks:
  #     - phegon-net
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "81:80"
  #   volumes:
  #     - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - auth-service
  #     - booking-service
  #     - room-service
  #   networks:
  #     - phegon-net


  
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=booking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - phegon-net

  # MySQL cho room
  mysql-room:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=room_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    networks:
      - phegon-net

  # MySQL cho user + auth
  mysql-user:
    image: mysql:8.0
    container_name: user_db_mysql
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    networks:
      - phegon-net

  # MinIO
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - phegon-net

networks:
  phegon-net:

volumes:
  minio-data:
